### PR TITLE
Add type annotations to assert.Equal calls

### PR DESCRIPTION
**Pull request by alexandercampbell-wf**
### Code Review

Fix what Testify broke, one more time.

@tylertreat-wf @seanstrickland-wf @blakewilson-wf

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
## SOC 1 Checklist
- [ ] All commits reviewed (e15f56f7536fb9f549c96c01b03e1784fa6fb824)
- [ ] QA Review
- [x] Security Review Completed if Applicable:  (N/A)

To remain in SOC1 Compliance the following users cannot merge this PR:
* alexandercampbell-wf

***
*Last updated on Wednesday, April 29 10:43 AM CST*

**Comment by tylertreat-wf** [comment]
+1

**Comment by seanstrickland-wf** [comment]
+1

**Comment by alexandercampbell-wf** [comment]
@tylertreat-wf @seanstrickland-wf can one of you merge? Thanks!

**Comment by travisreed-wf** [comment]
rosie

**Pull request merged**
