### PR TITLE
Add CORS middleware

### PR DESCRIPTION
**Pull request by tylertreat-wf**
This adds a CORS middleware extra which implements the Middleware
interface.

@thieupham-wf @stevenosborne-wf @alexandercampbell-wf @matthinrichsen-wf @seanstrickland-wf

### CODE REVIEW

**Comment by thieupham-wf** [comment]
+1

**Comment by matthinrichsen-wf** [comment]
+1

**Comment by stevenosborne-wf** [comment]
+1

**Comment by seanstrickland-wf** [comment]
+1

**Comment by travisreed-wf** [comment]
rosie

**Pull request merged**
